### ISSUE TITLE
Make publicly available?

### ISSUE THREAD

**Issue by Ihmoda** [joamjoamjoam/RemotePlayWhatever#1]
I've been running the master build of this on my deck and it's fantastic. Any plans to release this to the decky store?

**Comment by joamjoamjoam** [comment]
Yeah i think its just aboit ready for an alpha release. 

Ive been trying to solve some missing audio issues when playing games that dont use proton to run. But i think im gonna release it with a couple known issues. 

The two i know of is:
1. No sound when not using a proton game (stuff like yuzu retroarch etc)
2. You need to stop the RPT session before you try to close the game or it freezes sometimes. 
3. Can only invite one other player (RPW guy is going to fix this in the next release. 

If youve seen any more issues i should mention feel free to reply amd ill add them. 


Ill package it up and send it to the plugin store for verification tonight.

**Comment by Ihmoda** [comment]
I've run into an issue where I added a friend via the UI and it's definitely in the JSON, but the app doesn't seem to catch it until I restart. I also had some weirdness when I updated my decky-loader version, but recopying in the files seems to have fixed. Might just be an issue of how I pulled in the python/javascript files.

**Comment by joamjoamjoam** [comment]
are you using the zipped version? If so I updated the friends code to fix a couple issues. I just submitted the plugin to the store for verification.

Updating Decky might have an effect on the permission set on the appimage. I cant know for sure until it is accepted by the Decky team and I try it from the store. 

Here's the PR if you want to track the progress:

https://github.com/SteamDeckHomebrew/decky-plugin-database/pull/63

I gave the Friends stuff a good thrashing last night so Im confident it should be ready for release. If you still see issues after the store version let me know and ill take a look

**Comment by joamjoamjoam** [comment]
also not sure if you have a local copy of the repo but if you do I deleted the "master" branch and renamed the current stuff to main. So you might need to update the remotes and re-pull/re-track.

**Comment by Ihmoda** [comment]
My testing was with what you previously had on the master branch. I cloned the repo, checked out the master branch, ran the necessary pnpm commands and then copied over main.py and the compiled JavaScript into a directory in the homebrew/plugins folder with the expected decky structure.

Seems like it probably was a directory permissions issue following the Decky update. After updating Decky, only the "Start Remote Play Session" button was rendering. I went into the main.py and hardcoded in a friend ID JSON instead of loading the JSON from file and that worked, but while copying over the folder I ran chmod on some files in the directory.

After undoing my hardcoded changes, everything seemed to just work, so permissions issue tracks.

I can reliably reproduce the issue of adding a friend and them not showing up on the friend list, but could be due to my unique setup since I didn't start with a clean zip file.

**Comment by Ihmoda** [comment]
One other thing - I'm on the stable branch, haven't tried to test on Beta. I think the RPW dev may have mentioned that RPW isn't working on the beta channel of the Desktop Steam client. Not sure if the Steam Deck Client in beta channel is also beta and would not work.

**Comment by joamjoamjoam** [comment]
oh yeah the steam client beta branch doesnt work. Ill add that too

**Comment by joamjoamjoam** [comment]
Updated RPW to the latest version. Guest links are still a bit too crashy but i enabled inviting 3 players to the same session.
