### ISSUE TITLE
Can't get remote play link to send

### ISSUE THREAD

**Issue by TomCasavant** [joamjoamjoam/RemotePlayWhatever#3]
Maybe I'm missing a step somewhere,
I've added brawlhalla to my deck, I added a friend and gave them a nickname (I have their steamID64 but I have no idea where to input this information, which is probably where my issue is). Opened up a game, selected them for "Friend 1" and then clicked Start Remote Play Session. Nothing gets sent via chat, but I also don't see any errors or any other issues pop up.

**Comment by joamjoamjoam** [comment]
Yeah the latest steam client update broke remote play whatever. Im waiting on a fix for that project. 

Heres the issue if you want to add on to it. 

https://github.com/m4dEngi/RemotePlayWhatever/issues/78

**Comment by TomCasavant** [comment]
Awesome, thanks for the heads up

**Comment by Speedy2662** [comment]
Hi @joamjoamjoam, any progress on getting this tool working again? Just found out about it and it doesn't work for me! Happy to help test in any way I can.

**Comment by joamjoamjoam** [comment]
> Hi @joamjoamjoam, any progress on getting this tool working again? Just found out about it and it doesn't work for me! Happy to help test in any way I can.

Hey sorry for the delay. Unfortunately the project this plugin relies on seems to be abandoned. There were some potential workarounds but they all had serious drawbacks that made them unviable. (Sound not being shared saves being overwritten etc). If a viable alternative presents itself ill revive this plugin.
